export const navConfig = [
  {
    title: 'dialog component',
    list: [
      { name: 'dialog container', code: 'chat' },
      { name: 'bubble', code: 'bubble' },
      { name: 'card', code: 'card' },
      { name: 'file card', code: 'file-card' },
      { name: 'message status', code: 'message-status' },
      { name: 'system information', code: 'system-message' },
      { name: 'input (typing)', code: 'typing' },
    ],
  },
  {
    title: 'basic components',
    list: [
      { name: 'button', code: 'button' },
      { name: 'layout', code: 'flex' },
      { name: 'icon', code: 'icon' },
      { name: 'image', code: 'image' },
    ],
  },
  {
    title: 'form component',
    list: [
      { name: 'checkbox', code: 'checkbox' },
      { name: 'form', code: 'form' },
      { name: 'radio', code: 'radio' },
      { name: 'rate actions', code: 'rate-actions' },
      { name: 'input', code: 'input' },
      { name: 'search', code: 'search' },
      { name: 'selelctor', code: 'select' },
    ],
  },
  {
    title: 'Display components',
    list: [
      { name: '头像', code: 'avatar' },
      { name: '图片轮播', code: 'carousel' },
      { name: '分割线', code: 'divider' },
      { name: '空状态', code: 'empty' },
      { name: '列表', code: 'list' },
      { name: '导航', code: 'navbar' },
      { name: '公告', code: 'notice' },
      { name: '进度条', code: 'progress' },
      { name: '富文本', code: 'rich-text' },
      { name: '滚动容器', code: 'scroll-view' },
      { name: '步骤条', code: 'stepper' },
      { name: '标签页', code: 'tabs' },
      { name: '标签', code: 'tag' },
      { name: '文本', code: 'text' },
      { name: '时间', code: 'time' },
      { name: '视频', code: 'video' },
      { name: '媒体对象（废弃）', code: 'media-object' },
    ],
  },
  {
    title: 'feedback component',
    list: [
      { name: '无限滚动', code: 'infinite-scroll' },
      { name: '加载', code: 'Loading' },
      { name: '确认框', code: 'confirm' },
      { name: '模态框', code: 'modal' },
      { name: '上拉弹窗', code: 'popup' },
      { name: '下拉刷新', code: 'pull-to-refresh' },
      { name: '轻提示', code: 'toast' },
    ],
  },
  {
    title: 'business component',
    list: [
      { name: 'commodity card', code: 'goods' },
      { name: 'price', code: 'price' },
    ],
  },
  {
    title: 'other components',
    list: [
      { name: 'component loader', code: 'component-provider' },
      { name: 'error boundary', code: 'error-boundary' },
      { name: 'portal', code: 'portal' },
      { name: 'visually hidden', code: 'visually-hidden' },
    ],
  },
];
